FROM ubuntu:18.04
MAINTAINER Manish Singh

#User root
RUN apt update -y && apt upgrade -y
RUN apt install software-properties-common -y
RUN add-apt-repository ppa:jonathonf/ffmpeg-4
RUN apt install ffmpeg -y

# ENTRYPOINT ["/bin/sh"]
CMD ["echo use docker run --rm -t ubuntu/s/ffmpeg ffmpeg"]