FROM ubuntu:18.04
MAINTAINER Manish Singh

#User root
RUN apt update -y && apt upgrade -y
RUN apt install openssh-client openssh-server nmap -y
RUN apt install pandoc -y

# ENTRYPOINT ["/bin/sh"]
CMD ["echo use docker run --rm -t ubuntu/s/u ssh|nmap|pandoc"]
